ex01:
  gemini_model: gemini-3.6-flash
  mode: stream  # text | stream
ex02:
  force_initialize: false
  select_category: consumable-perishables  # consumable-perishables | consumable-nonperishables | general-merchandise | specific-brands | severe-issues | clothing-footwear
  query_with_used_words: How do I raise a complaint?
  search_2: What are the clothing rules?
